### ISSUE TITLE
week 01 回覆

### ISSUE THREAD

**Issue by azole** [I-Sheng/git-practice#1]
請補交 git.md 這份作業:
- 試著學習找到的資料後，用「自己的理解」來回答問題，而不是複製貼上答案。
- Experience 這一部分你想表達的是？
- commit message 這題沒有回答到

另外，「而沒有趣探討如何處理大流量應用或維運」 -> 有錯字，在想要學習所謂的大流量或其他進階技能前，要先把基礎功打好，要站穩。

逸盛，如果我沒有看錯的話，你已經大四了對嗎？ 如果沒有要考研究所，那也即將要開始求職，坦誠地跟你說，你這份作業的品質非常不 ok，希望你能從這份作業開始，練習做更深入的思考，這個思考包括技術層次，也包括表達這樣的軟技能，對你未來的職涯會有幫助的。

補交期限: 9/21 六 23:00 前

**Comment by I-Sheng** [comment]
老師不好意思，

原本我不太清楚要以什麼方式來呈現git的那些概念，所以才進行了實驗的部分。
了解老師的意思後，我已經根據我的理解進行了修正，並且增加了commit message的內容

**Comment by azole** [comment]
好，很好喔，我看你有準備 branch modeling，怎麼不試試看在課堂上分享？

**Comment by I-Sheng** [comment]
> 好，很好喔，我看你有準備 branch modeling，怎麼不試試看在課堂上分享？

老師上課問的時候我有想過要不要去，但是看到大家一片沉默，就想說如果被老師叫到再上去分享!

**Comment by azole** [comment]
下次挑戰自己一下，主動上台試試看！（當一下我的暗樁嘛）

ps. 如果沒有其他需要跟我討論的事，這個 issue 可以 close 了。

**Comment by I-Sheng** [comment]
了解，感謝老師!
